-- supabase/migrations/20260828164502_align_mensalidades_id_identity_column.sql
--
-- PED-49 — corrige drift de schema staging x produção em mensalidades.id.
--
-- Achado durante a revisão final do PED-27: staging (projeto recriado
-- em 2026-08-25, já a partir do baseline squashed) tem mensalidades.id
-- como identity column (`generated by default as identity`), enquanto
-- produção (projeto original, de 2026-06-14) ainda tem a coluna no
-- formato serial clássico (`default nextval('mensalidades_id_seq')`).
-- O baseline atual (supabase/migrations/00000000000000_baseline_current_schema.sql,
-- linha ~252) já usa identity column — ou seja, produção é o ambiente
-- desalinhado, não staging. Confirmado por inspeção direta via MCP do
-- Supabase nos dois projetos (qjmybxkfjkxttggdjxga x tciiepqmnrrcjnqhspvw)
-- antes de escrever esta migration.
--
-- Não é destrutiva: mantém o mesmo tipo (bigint), mesma numeração (o
-- identity novo assume START WITH exatamente o próximo valor que a
-- sequence antiga entregaria — sem gap, sem colisão com ids existentes)
-- e o mesmo comportamento de auto-geração no insert. Nenhuma function
-- especifica `id` explicitamente (ver descrição do PED-49), então nada
-- no código depende do mecanismo antigo.
--
-- Idempotente: o bloco só age se a coluna ainda não for identity, então
-- rodar isto em staging (já convertida) é no-op — necessário porque
-- `supabase db push` aplica todas as migrations pendentes a qualquer
-- ambiente linkado, staging ou produção.
do $$
declare
  v_next bigint;
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.mensalidades'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    -- nextval() consome o próximo valor da sequence antiga; ele vira o
    -- START WITH do identity novo, então não é desperdiçado.
    select nextval(pg_get_serial_sequence('public.mensalidades', 'id')) into v_next;

    execute 'alter table public.mensalidades alter column id drop default';
    execute format(
      'alter table public.mensalidades alter column id add generated by default as identity (start with %s)',
      v_next
    );
    execute 'drop sequence if exists public.mensalidades_id_seq';
  end if;
end $$;
