-- supabase/migrations/20260829150000_align_despesas_feriados_planos_id_identity_column.sql
--
-- PED-71 — corrige drift de schema staging x produção em despesas.id,
-- feriados.id e planos.id. Mesmo padrão do PED-49 (mensalidades.id):
-- staging (projeto recriado em 2026-08-25, já a partir do baseline
-- squashed atual) tem essas 3 colunas como identity column (`generated
-- by default as identity`), enquanto produção (projeto original, de
-- 2026-06-14) ainda tem cada uma no formato serial clássico (`default
-- nextval(...)`). O baseline atual
-- (supabase/migrations/00000000000000_baseline_current_schema.sql) já
-- declara as 3 como identity — produção é quem ficou desalinhada, não
-- staging. Confirmado por inspeção direta via MCP do Supabase nos dois
-- projetos (qjmybxkfjkxttggdjxga x tciiepqmnrrcjnqhspvw) antes de
-- escrever esta migration.
--
-- Não é destrutiva: mantém o mesmo tipo (bigint), mesma numeração (o
-- identity novo assume START WITH exatamente o próximo valor que a
-- sequence antiga entregaria — sem gap, sem colisão com ids existentes)
-- e o mesmo comportamento de auto-geração no insert. Nenhuma function em
-- supabase/migrations/ especifica `id` explicitamente no insert de
-- despesas/feriados/planos (grep feito antes de escrever esta migration,
-- mesma checagem do PED-49), então nada no código depende do mecanismo
-- antigo.
--
-- Idempotente: cada bloco só age se a coluna correspondente ainda não for
-- identity, então rodar isto num ambiente já convertido (ex: staging) é
-- no-op — necessário porque `supabase db push` aplica todas as migrations
-- pendentes a qualquer ambiente linkado, staging ou produção.
do $$
declare
  v_next bigint;
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.despesas'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    select nextval(pg_get_serial_sequence('public.despesas', 'id')) into v_next;

    execute 'alter table public.despesas alter column id drop default';
    execute format(
      'alter table public.despesas alter column id add generated by default as identity (start with %s)',
      v_next
    );
    execute 'drop sequence if exists public.despesas_id_seq';
  end if;
end $$;

do $$
declare
  v_next bigint;
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.feriados'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    select nextval(pg_get_serial_sequence('public.feriados', 'id')) into v_next;

    execute 'alter table public.feriados alter column id drop default';
    execute format(
      'alter table public.feriados alter column id add generated by default as identity (start with %s)',
      v_next
    );
    execute 'drop sequence if exists public.feriados_id_seq';
  end if;
end $$;

do $$
declare
  v_next bigint;
begin
  if not exists (
    select 1
    from pg_attribute
    where attrelid = 'public.planos'::regclass
      and attname = 'id'
      and attidentity <> ''
  ) then
    select nextval(pg_get_serial_sequence('public.planos', 'id')) into v_next;

    execute 'alter table public.planos alter column id drop default';
    execute format(
      'alter table public.planos alter column id add generated by default as identity (start with %s)',
      v_next
    );
    execute 'drop sequence if exists public.planos_id_seq';
  end if;
end $$;
