-- supabase/migrations/20260913200000_lista_espera_automatica.sql
-- Lista de espera automática para turma lotada (roadmap Nexofy HQ,
-- 2026-09-10 — nenhum dos 5 concorrentes analisados documenta o recurso).
-- Ver docs/superpowers/specs/2026-09-13-lista-espera-turma-lotada-design.md.

-- ============================================================================
-- TABELA
-- ============================================================================
create table public.lista_espera (
  id bigint generated by default as identity primary key,
  estudio_id uuid not null references public.estudios(id),
  aula_id bigint not null references public.agenda(id),
  data_aula date not null,
  aluno_id bigint not null references public.alunos(id),
  status text not null default 'aguardando'
    check (status in ('aguardando', 'convertido', 'cancelado', 'expirado')),
  criado_em timestamptz not null default now(),
  promovido_em timestamptz,
  notificado_em timestamptz,
  presenca_id bigint references public.presencas(id),
  motivo_saida text
);

comment on table public.lista_espera is
  'Fila de espera por turma+data lotada. Promoção automática via trigger em presencas (ver promover_fila_apos_liberar_vaga).';

-- só 1 entrada ativa por aluno/turma/data; permite reentrar depois de sair/expirar
create unique index lista_espera_ativa_uniq on public.lista_espera
  (estudio_id, aula_id, data_aula, aluno_id) where (status = 'aguardando');

create index lista_espera_fila_idx on public.lista_espera
  (estudio_id, aula_id, data_aula, status, criado_em);

alter table public.lista_espera enable row level security;

create policy lista_espera_select_estudio on public.lista_espera
  as permissive for select to public
  using (
    (estudio_id in (select em.estudio_id from estudio_membros em where em.user_id = (select auth.uid())))
    or exists (select 1 from estudio_membros em where em.user_id = (select auth.uid()) and em.role = 'super_admin')
  );

create policy lista_espera_insert_estudio on public.lista_espera
  as permissive for insert to public
  with check (
    (estudio_id in (select em.estudio_id from estudio_membros em where em.user_id = (select auth.uid()) and em.role = any(array['admin','professor'])))
    or exists (select 1 from estudio_membros em where em.user_id = (select auth.uid()) and em.role = 'super_admin')
  );

create policy lista_espera_update_estudio on public.lista_espera
  as permissive for update to public
  using (
    (estudio_id in (select em.estudio_id from estudio_membros em where em.user_id = (select auth.uid()) and em.role = any(array['admin','professor'])))
    or exists (select 1 from estudio_membros em where em.user_id = (select auth.uid()) and em.role = 'super_admin')
  );

create policy lista_espera_delete_estudio on public.lista_espera
  as permissive for delete to public
  using (
    (estudio_id in (select em.estudio_id from estudio_membros em where em.user_id = (select auth.uid()) and em.role = any(array['admin','professor'])))
    or exists (select 1 from estudio_membros em where em.user_id = (select auth.uid()) and em.role = 'super_admin')
  );

-- ============================================================================
-- HELPER COMPARTILHADO — extraído de verificar_disponibilidade_v2 (evita
-- duplicar a query de ocupação na função de promoção da fila abaixo).
-- ============================================================================
create or replace function public.calcular_ocupacao_turma(
  p_aula_id bigint,
  p_data date,
  p_estudio_id uuid
)
returns table(ocupacao_atual int, capacidade_max int)
language plpgsql
set search_path to 'public'
as $function$
declare
  v_capacidade_padrao int;
  v_capacidade_agenda int;
  v_qtd_avulsos int;
  v_qtd_fixos int;
  v_existe boolean;
begin
  select true, a.capacidade, m.capacidade_padrao
  into v_existe, v_capacidade_agenda, v_capacidade_padrao
  from agenda a
  left join modalidades m on m.id = a.modalidade_id
  where a.id = p_aula_id
    and a.estudio_id = p_estudio_id;

  if not coalesce(v_existe, false) then
    raise exception 'Aula não encontrada no banco de dados.';
  end if;

  select count(*) into v_qtd_avulsos
  from presencas p
  where p.aula_id = p_aula_id
    and p.estudio_id = p_estudio_id
    and p.data_aula = p_data
    and p.origem in ('avulso', 'lead')
    and p.status in ('agendado', 'presente');

  select count(*) into v_qtd_fixos
  from agenda_fixa af
  where af.aula_id = p_aula_id
    and af.estudio_id = p_estudio_id
    and not exists (
      select 1 from presencas p
      where p.aluno_id = af.aluno_id
        and p.aula_id = p_aula_id
        and p.estudio_id = p_estudio_id
        and p.data_aula = p_data
        and p.origem = 'fixo'
        and p.status in ('falta_justificada', 'falta_nao_avisada')
    );

  ocupacao_atual := coalesce(v_qtd_avulsos, 0) + coalesce(v_qtd_fixos, 0);
  capacidade_max := coalesce(v_capacidade_padrao, v_capacidade_agenda, 15);
  return next;
end;
$function$;

-- ============================================================================
-- REFATORAÇÃO: verificar_disponibilidade_v2 passa a usar o helper acima em
-- vez de duplicar a query de ocupação. Shape de retorno (jsonb) inalterado.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.verificar_disponibilidade_v2(p_aula_id bigint, p_data date, p_estudio_id uuid, p_aluno_id bigint DEFAULT NULL::bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
    v_mod_id uuid;
    v_mod_nome text;
    v_mod_area text;
    v_existe_aula boolean;

    v_capacidade_max int;
    v_ocupacao_atual int;

    v_aviso text := null;
    v_aviso_lotacao text := null;
    v_aviso_plano text := null;

    v_aluno RECORD;
    v_plano RECORD;
    v_regra_area jsonb := NULL;
    v_is_livre boolean := false;
    v_tem_mod_no_plano boolean := true;
    v_limite_semanal int := 0;
    v_uso_semanal int := 0;

    v_uso_agendados int := 0;
    v_uso_fixos int := 0;
BEGIN
    IF p_estudio_id IS NULL THEN
        RAISE EXCEPTION 'p_estudio_id é obrigatório.';
    END IF;

    IF NOT ( (select public.estudio_id_atual()) = p_estudio_id OR (select public.eh_super_admin()) ) THEN
        RAISE EXCEPTION 'Acesso negado: usuário não pertence a este estúdio.' USING errcode = '42501';
    END IF;

    SELECT true, m.id, COALESCE(m.nome, 'Atividade'), m.area
    INTO v_existe_aula, v_mod_id, v_mod_nome, v_mod_area
    FROM agenda a
    LEFT JOIN modalidades m ON m.id = a.modalidade_id
    WHERE a.id = p_aula_id
      AND a.estudio_id = p_estudio_id;

    IF NOT COALESCE(v_existe_aula, false) THEN
        RAISE EXCEPTION 'Aula não encontrada no banco de dados.';
    END IF;

    SELECT ocupacao_atual, capacidade_max
    INTO v_ocupacao_atual, v_capacidade_max
    FROM public.calcular_ocupacao_turma(p_aula_id, p_data, p_estudio_id);

    IF v_ocupacao_atual >= v_capacidade_max THEN
        v_aviso_lotacao := 'Esta turma já está lotada! Capacidade máxima: ' || v_capacidade_max || ' vagas. Deseja forçar o agendamento mesmo assim?';
    END IF;

    IF p_aluno_id IS NOT NULL THEN
        SELECT modalidades_selecionadas, plano_id
        INTO v_aluno
        FROM alunos
        WHERE id = p_aluno_id
          AND estudio_id = p_estudio_id;

        IF v_aluno.plano_id IS NOT NULL THEN
            SELECT regras_acesso
            INTO v_plano
            FROM planos
            WHERE id = v_aluno.plano_id
              AND estudio_id = p_estudio_id;

            IF v_plano.regras_acesso IS NOT NULL AND jsonb_typeof(v_plano.regras_acesso) = 'array' THEN
                SELECT elem INTO v_regra_area
                FROM jsonb_array_elements(v_plano.regras_acesso) AS elem
                WHERE elem->>'modalidade' = v_mod_area
                LIMIT 1;
            END IF;

            IF v_regra_area IS NULL THEN
                v_aviso_plano := 'Atenção: O plano atual do aluno NÃO permite acesso à área de "' || COALESCE(v_mod_area, 'Desconhecida') || '". Deseja forçar a entrada mesmo assim?';
                v_tem_mod_no_plano := false;
            ELSE
                v_limite_semanal := COALESCE((v_regra_area->>'limite')::int, 0);
                v_is_livre := (v_limite_semanal = 999);

                IF NOT v_is_livre AND (COALESCE(v_aluno.modalidades_selecionadas::text, '') NOT LIKE '%' || v_mod_id::text || '%') THEN
                    v_aviso_plano := 'Atenção: O aluno não possui a modalidade "' || v_mod_nome || '" ativa no perfil dele. Deseja forçar?';
                    v_tem_mod_no_plano := false;
                ELSIF NOT v_is_livre THEN

                    SELECT count(*) INTO v_uso_agendados
                    FROM presencas p
                    JOIN agenda ag ON ag.id = p.aula_id
                    JOIN modalidades mo ON mo.id = ag.modalidade_id
                    WHERE p.aluno_id = p_aluno_id
                      AND p.estudio_id = p_estudio_id
                      AND p.origem IN ('avulso', 'lead')
                      AND p.status IN ('agendado', 'presente')
                      AND mo.area = v_mod_area
                      AND date_trunc('week', p.data_aula::timestamp) = date_trunc('week', p_data::timestamp)
                      AND NOT EXISTS (
                          SELECT 1 FROM feriados f
                          WHERE f.data = p.data_aula
                            AND f.estudio_id = p_estudio_id
                            AND f.bloqueia_agenda = true
                      );

                    SELECT count(*) INTO v_uso_fixos
                    FROM agenda_fixa af2
                    JOIN agenda ag ON ag.id = af2.aula_id
                    JOIN modalidades mo ON mo.id = ag.modalidade_id
                    WHERE af2.aluno_id = p_aluno_id
                      AND af2.estudio_id = p_estudio_id
                      AND mo.area = v_mod_area
                      AND NOT EXISTS (
                          SELECT 1 FROM feriados f
                          WHERE f.bloqueia_agenda = true
                            AND f.estudio_id = p_estudio_id
                            AND f.data >= date_trunc('week', p_data::timestamp)::date
                            AND f.data <= (date_trunc('week', p_data::timestamp) + interval '6 days')::date
                            AND EXTRACT(DOW FROM f.data) = CASE LOWER(ag.dia_semana)
                                WHEN 'domingo'       THEN 0
                                WHEN 'segunda-feira' THEN 1
                                WHEN 'terça-feira'   THEN 2
                                WHEN 'quarta-feira'  THEN 3
                                WHEN 'quinta-feira'  THEN 4
                                WHEN 'sexta-feira'   THEN 5
                                WHEN 'sábado'        THEN 6
                            END
                      )
                      AND NOT EXISTS (
                          SELECT 1 FROM presencas p
                          WHERE p.aluno_id = af2.aluno_id
                            AND p.aula_id = af2.aula_id
                            AND p.estudio_id = p_estudio_id
                            AND p.origem = 'fixo'
                            AND p.status IN ('falta_justificada', 'falta_nao_avisada')
                            AND date_trunc('week', p.data_aula::timestamp) = date_trunc('week', p_data::timestamp)
                      );

                    v_uso_semanal := COALESCE(v_uso_agendados, 0) + COALESCE(v_uso_fixos, 0);

                    IF v_uso_semanal >= v_limite_semanal AND v_limite_semanal > 0 THEN
                        v_aviso_plano := 'O aluno já atingiu o limite de ' || v_limite_semanal || 'x aulas na semana para a área de ' || COALESCE(v_mod_area, 'Desconhecida') || '. Deseja agendar assim mesmo?';
                    END IF;
                END IF;
            END IF;
        ELSE
            v_aviso_plano := 'Este aluno não possui um plano ativo vinculado. Deseja forçar o agendamento?';
            v_tem_mod_no_plano := false;
        END IF;
    END IF;

    IF v_aviso_plano IS NOT NULL AND v_aviso_lotacao IS NOT NULL THEN
        v_aviso := v_aviso_lotacao || ' ' || v_aviso_plano;
    ELSE
        v_aviso := COALESCE(v_aviso_plano, v_aviso_lotacao);
    END IF;

    RETURN jsonb_build_object(
        'podeAgendarLivremente', (v_aviso IS NULL),
        'avisoCritico', v_aviso,
        'capacidadeMax', v_capacidade_max,
        'ocupacaoAtual', v_ocupacao_atual,
        'limiteSemanal', v_limite_semanal,
        'usoSemanal', v_uso_semanal,
        'isLivre', v_is_livre,
        'modNome', v_mod_nome,
        'temModalidadeNoPlano', v_tem_mod_no_plano
    );
END;
$function$
;

-- ============================================================================
-- RPCs — SUPERFÍCIE DO ALUNO (SECURITY DEFINER, mesmo padrão de
-- agendar_avulso: próprio aluno OU staff do estúdio; auth.uid() is null
-- nunca deve "casar" com alunos.auth_id is null, ver migration 20260909191500).
-- ============================================================================
create or replace function public.entrar_lista_espera(
  p_estudio_id uuid,
  p_aluno_id bigint,
  p_aula_id bigint,
  p_data_aula date
)
returns lista_espera
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_pode_gerenciar boolean;
  v_auth_id_aluno uuid;
  v_ocupacao_atual int;
  v_capacidade_max int;
  v_ja_agendado boolean;
  v_resultado lista_espera;
begin
  if p_estudio_id is null then
    raise exception 'p_estudio_id é obrigatório.';
  end if;
  if p_aula_id is null or p_data_aula is null or p_aluno_id is null then
    raise exception 'p_aluno_id, p_aula_id e p_data_aula são obrigatórios.';
  end if;

  select exists (
    select 1 from estudio_membros em
    where em.user_id = auth.uid()
      and em.estudio_id = p_estudio_id
      and em.role in ('admin', 'professor', 'super_admin')
  ) into v_pode_gerenciar;

  if not v_pode_gerenciar then
    select auth_id into v_auth_id_aluno
    from alunos
    where id = p_aluno_id and estudio_id = p_estudio_id;

    if auth.uid() is null or v_auth_id_aluno is distinct from auth.uid() then
      raise exception 'Acesso negado: você só pode entrar na lista de espera para si mesmo.';
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_aula_id::text || '|' || p_data_aula::text, 0));

  select exists (
    select 1 from presencas
    where aluno_id = p_aluno_id and aula_id = p_aula_id and data_aula = p_data_aula
      and estudio_id = p_estudio_id and status in ('agendado', 'presente')
  ) into v_ja_agendado;

  if v_ja_agendado then
    raise exception 'Você já está agendado nesta turma.';
  end if;

  if exists (
    select 1 from lista_espera
    where aluno_id = p_aluno_id and aula_id = p_aula_id and data_aula = p_data_aula
      and estudio_id = p_estudio_id and status = 'aguardando'
  ) then
    raise exception 'Você já está na lista de espera desta turma.';
  end if;

  select ocupacao_atual, capacidade_max
  into v_ocupacao_atual, v_capacidade_max
  from public.calcular_ocupacao_turma(p_aula_id, p_data_aula, p_estudio_id);

  if v_ocupacao_atual < v_capacidade_max then
    raise exception 'Esta turma ainda tem vagas — agende diretamente em vez de entrar na lista de espera.';
  end if;

  insert into lista_espera (estudio_id, aula_id, data_aula, aluno_id)
  values (p_estudio_id, p_aula_id, p_data_aula, p_aluno_id)
  returning * into v_resultado;

  return v_resultado;
end;
$function$;

revoke execute on function public.entrar_lista_espera(uuid, bigint, bigint, date) from public;
grant execute on function public.entrar_lista_espera(uuid, bigint, bigint, date) to authenticated;
grant execute on function public.entrar_lista_espera(uuid, bigint, bigint, date) to service_role;

create or replace function public.sair_lista_espera(
  p_estudio_id uuid,
  p_lista_espera_id bigint
)
returns json
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_linha lista_espera;
  v_pode_gerenciar boolean;
  v_auth_id_aluno uuid;
begin
  if p_estudio_id is null or p_lista_espera_id is null then
    raise exception 'p_estudio_id e p_lista_espera_id são obrigatórios.';
  end if;

  select * into v_linha
  from lista_espera
  where id = p_lista_espera_id and estudio_id = p_estudio_id;

  if v_linha is null then
    return json_build_object('sucesso', false, 'mensagem', 'Entrada na lista de espera não encontrada.');
  end if;

  select exists (
    select 1 from estudio_membros em
    where em.user_id = auth.uid()
      and em.estudio_id = p_estudio_id
      and em.role in ('admin', 'professor', 'super_admin')
  ) into v_pode_gerenciar;

  if not v_pode_gerenciar then
    select auth_id into v_auth_id_aluno
    from alunos
    where id = v_linha.aluno_id and estudio_id = p_estudio_id;

    if auth.uid() is null or v_auth_id_aluno is distinct from auth.uid() then
      raise exception 'Acesso negado: você só pode sair da sua própria lista de espera.';
    end if;
  end if;

  if v_linha.status <> 'aguardando' then
    return json_build_object('sucesso', false, 'mensagem', 'Esta entrada já não está mais aguardando.');
  end if;

  update lista_espera
    set status = 'cancelado',
        motivo_saida = case when v_pode_gerenciar then 'removido_pelo_estudio' else 'cancelado_pelo_aluno' end
    where id = p_lista_espera_id;

  return json_build_object('sucesso', true, 'mensagem', 'Removido da lista de espera com sucesso.');
end;
$function$;

revoke execute on function public.sair_lista_espera(uuid, bigint) from public;
grant execute on function public.sair_lista_espera(uuid, bigint) to authenticated;
grant execute on function public.sair_lista_espera(uuid, bigint) to service_role;

create or replace function public.listar_minha_fila(
  p_estudio_id uuid,
  p_aluno_id bigint
)
returns table (
  id bigint,
  aula_id bigint,
  data_aula date,
  status text,
  criado_em timestamptz,
  posicao bigint,
  atividade text,
  horario time
)
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_pode_gerenciar boolean;
  v_auth_id_aluno uuid;
begin
  if p_estudio_id is null or p_aluno_id is null then
    raise exception 'p_estudio_id e p_aluno_id são obrigatórios.';
  end if;

  select exists (
    select 1 from estudio_membros em
    where em.user_id = auth.uid()
      and em.estudio_id = p_estudio_id
      and em.role in ('admin', 'professor', 'super_admin')
  ) into v_pode_gerenciar;

  if not v_pode_gerenciar then
    select auth_id into v_auth_id_aluno
    from alunos
    where id = p_aluno_id and estudio_id = p_estudio_id;

    if auth.uid() is null or v_auth_id_aluno is distinct from auth.uid() then
      raise exception 'Acesso negado: você só pode ver a própria lista de espera.';
    end if;
  end if;

  return query
  select
    le.id, le.aula_id, le.data_aula, le.status, le.criado_em,
    case when le.status = 'aguardando' then (
      select count(*) + 1 from lista_espera le2
      where le2.estudio_id = le.estudio_id
        and le2.aula_id = le.aula_id
        and le2.data_aula = le.data_aula
        and le2.status = 'aguardando'
        and le2.criado_em < le.criado_em
    ) else null end as posicao,
    ag.atividade, ag.horario
  from lista_espera le
  join agenda ag on ag.id = le.aula_id
  where le.estudio_id = p_estudio_id
    and le.aluno_id = p_aluno_id
    and (le.status = 'aguardando' or le.criado_em > now() - interval '7 days')
  order by le.criado_em desc;
end;
$function$;

revoke execute on function public.listar_minha_fila(uuid, bigint) from public;
grant execute on function public.listar_minha_fila(uuid, bigint) to authenticated;
grant execute on function public.listar_minha_fila(uuid, bigint) to service_role;

-- ============================================================================
-- PROMOÇÃO AUTOMÁTICA — dispara sempre que uma mudança em `presencas` pode
-- ter liberado uma vaga (cancelamento, falta registrada, falta antecipada
-- de matrícula fixa). Mesmo advisory lock de agendar_avulso, pra serializar
-- com um booking concorrente disputando a mesma vaga.
-- ============================================================================
create or replace function public.promover_fila_apos_liberar_vaga()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_estudio_id uuid;
  v_aula_id bigint;
  v_data_aula date;
  v_libera boolean := false;

  v_ocupacao_atual int;
  v_capacidade_max int;
  v_candidato record;
  v_disp jsonb;
  v_dias_atraso int;
  v_tolerancia int;
  v_presenca_id bigint;
  v_iteracoes int := 0;
begin
  if TG_OP = 'DELETE' then
    if OLD.origem in ('avulso', 'lead') and OLD.status in ('agendado', 'presente') then
      v_libera := true;
      v_estudio_id := OLD.estudio_id;
      v_aula_id := OLD.aula_id;
      v_data_aula := OLD.data_aula;
    end if;
  elsif TG_OP = 'UPDATE' then
    if NEW.origem in ('avulso', 'lead')
       and OLD.status in ('agendado', 'presente')
       and NEW.status in ('falta_justificada', 'falta_nao_avisada') then
      v_libera := true;
      v_estudio_id := NEW.estudio_id;
      v_aula_id := NEW.aula_id;
      v_data_aula := NEW.data_aula;
    end if;
  elsif TG_OP = 'INSERT' then
    if NEW.origem = 'fixo' and NEW.status in ('falta_justificada', 'falta_nao_avisada') then
      v_libera := true;
      v_estudio_id := NEW.estudio_id;
      v_aula_id := NEW.aula_id;
      v_data_aula := NEW.data_aula;
    end if;
  end if;

  if not v_libera or v_data_aula < current_date then
    return coalesce(NEW, OLD);
  end if;

  perform pg_advisory_xact_lock(hashtextextended(v_aula_id::text || '|' || v_data_aula::text, 0));

  loop
    v_iteracoes := v_iteracoes + 1;
    exit when v_iteracoes > 50;

    select ocupacao_atual, capacidade_max
    into v_ocupacao_atual, v_capacidade_max
    from public.calcular_ocupacao_turma(v_aula_id, v_data_aula, v_estudio_id);

    exit when v_ocupacao_atual >= v_capacidade_max;

    select * into v_candidato
    from public.lista_espera
    where estudio_id = v_estudio_id
      and aula_id = v_aula_id
      and data_aula = v_data_aula
      and status = 'aguardando'
    order by criado_em asc
    limit 1;

    exit when v_candidato is null;

    select dias_atraso into v_dias_atraso
    from alunos where id = v_candidato.aluno_id and estudio_id = v_estudio_id;

    select dias_tolerancia_inadimplencia into v_tolerancia
    from estudios where id = v_estudio_id;

    if coalesce(v_dias_atraso, 0) > coalesce(v_tolerancia, 5) then
      update public.lista_espera
        set status = 'expirado', motivo_saida = 'inadimplente'
        where id = v_candidato.id;
      continue;
    end if;

    v_disp := public.verificar_disponibilidade_v2(v_aula_id, v_data_aula, v_estudio_id, v_candidato.aluno_id);

    if (v_disp->>'podeAgendarLivremente')::boolean is false then
      update public.lista_espera
        set status = 'expirado', motivo_saida = 'fora_do_plano'
        where id = v_candidato.id;
      continue;
    end if;

    begin
      insert into public.presencas (estudio_id, aluno_id, aula_id, data_aula, origem, status)
      values (v_estudio_id, v_candidato.aluno_id, v_aula_id, v_data_aula, 'avulso', 'agendado')
      returning id into v_presenca_id;

      update public.lista_espera
        set status = 'convertido', promovido_em = now(), presenca_id = v_presenca_id
        where id = v_candidato.id;
    exception
      when unique_violation then
        -- candidato já tinha um agendamento concorrente pra essa turma/data;
        -- bloco aninhado (savepoint próprio) pra não derrubar promoções já
        -- confirmadas em iterações anteriores deste mesmo loop.
        update public.lista_espera
          set status = 'expirado', motivo_saida = 'conflito_de_agendamento'
          where id = v_candidato.id;
    end;
  end loop;

  return coalesce(NEW, OLD);
end;
$function$;

create trigger trg_promover_fila_apos_liberar_vaga
after insert or update or delete on public.presencas
for each row execute function public.promover_fila_apos_liberar_vaga();
